"""initial migration

Revision ID: 72af35b254e0
Revises: 
Create Date: 2026-04-10 09:49:03.244070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72af35b254e0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('api_key', sa.String(), nullable=False),
    sa.Column('base_url', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_digests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('sections', sa.JSON(), nullable=True),
    sa.Column('total_articles_processed', sa.Integer(), nullable=True),
    sa.Column('anchor_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    # GIN index removed - requires JSONB type. Can be added later with proper migration.
    op.create_table('digest_feedback',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('digest_id', sa.Integer(), nullable=False),
    sa.Column('anchor_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fetch_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('news_sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=True),
    sa.Column('api_base_url', sa.String(), nullable=False),
    sa.Column('auth_key', sa.String(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_fetch_at', sa.DateTime(), nullable=True),
    sa.Column('article_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_behavior_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('digest_id', sa.Integer(), nullable=True),
    sa.Column('anchor_id', sa.Integer(), nullable=True),
    sa.Column('tag', sa.String(), nullable=True),
    sa.Column('signal_type', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_interest_tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tag', sa.String(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('show_count', sa.Integer(), nullable=True),
    sa.Column('hide_count', sa.Integer(), nullable=True),
    sa.Column('total_time_spent', sa.Float(), nullable=True),
    sa.Column('click_count', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tag')
    )
    op.create_table('articles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['news_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('anchor_points',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('dialectical_analysis', sa.Text(), nullable=True),
    sa.Column('anchor_type', sa.String(), nullable=True),
    sa.Column('significance', sa.Float(), nullable=True),
    sa.Column('source_article_title', sa.String(), nullable=True),
    sa.Column('source_article_link', sa.String(), nullable=True),
    sa.Column('source_name', sa.String(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('related_tag_weights', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # GIN indexes removed - require JSONB type. Can be added later with proper migration.
    # op.create_index('idx_anchor_related_weights', 'anchor_points', ['related_tag_weights'], unique=False, postgresql_using='gin')
    # op.create_index('idx_anchor_tags', 'anchor_points', ['tags'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_anchor_tags', table_name='anchor_points', postgresql_using='gin')
    op.drop_index('idx_anchor_related_weights', table_name='anchor_points', postgresql_using='gin')
    op.drop_table('anchor_points')
    op.drop_table('articles')
    op.drop_table('user_interest_tags')
    op.drop_table('user_behavior_logs')
    op.drop_table('news_sources')
    op.drop_table('fetch_logs')
    op.drop_table('digest_feedback')
    op.drop_index('idx_digest_sections', table_name='daily_digests', postgresql_using='gin')
    op.drop_table('daily_digests')
    op.drop_table('ai_config')
    # ### end Alembic commands ###
